"""add language to posts

Revision ID: 604a19eb9e78
Revises: 1a4f3600a83f
Create Date: 2019-08-09 15:21:57.623327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604a19eb9e78'
down_revision = '1a4f3600a83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
