"""new fields in user model

Revision ID: 847c23385443
Revises: bc3c32912e45
Create Date: 2019-05-07 22:06:37.878273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c23385443'
down_revision = 'bc3c32912e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
